module.exports = {
	printWidth: 80,
	tabWidth: 4,
	useTabs: true,
	semi: false,
	singleQuote: true,
	trailingComma: 'all',
	bracketSpacing: false,
	arrowParens: 'avoid',
	endOfLine: 'lf',
	quoteProps: 'as-needed',
	proseWrap: 'preserve',
	htmlWhitespaceSensitivity: 'css',
	jsxSingleQuote: true,
	jsxBracketSameLine: false,
}
