#!/bin/bash
set -ex

git checkout generator
yarn && yarn run tsc && node dist/index.js
mkdir /tmp/site_build
cp -r build/* /tmp/site_build
git checkout master
rm -rf *
git restore README.md CNAME
mv /tmp/site_build/* .
rm -rf /tmp/site_build
git add .
git commit -m "GoodCommitMessage™"
git push origin master
git checkout generator

