name: Build page
on: push
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Build page
      run: |
        echo "Hello"
        echo "World"
        echo $(ls -la)
        echo $(pwd)
